### ISSUE TITLE
[Idea] More straightforward Brain Extraction from severed head

### ISSUE THREAD

**Issue by Dagreenskin** [Sierracode/-tg-station#106]
Its kinda silly having to retransplant a head onto a body just to extract the brain from it, so using a circular saw or ghetto equivalent (Like an armblade) on a severed head should extract the brain but destroy the head in the process.

**Comment by Zaers** [comment]
Using a circular saw on a severed head already should remove the brain from it (see https://github.com/Sierracode/-tg-station/blob/master/code/modules/organs/organs_external.dm#L119) but the ghetto alternatives to the saw should probably be added to that too
