### ISSUE TITLE
[IDEA] Wizard "Headhunting"

### ISSUE THREAD

**Issue by Dagreenskin** [Sierracode/-tg-station#107]
Now that we have dismemberment, wizards should be able to have the objective "BRING US THE HEAD OF X" Not only is this more interesting than straight up murder, but Ei'nath wizards will have to be cautious not to screw themselves over by gibbing someone they need the head of. You could even give the ritual knife thats on the wizard ship higher limb damage for that purpose.

**Comment by chaosyourgod** [comment]
I think that we should get predators off of either CM or /TG/ instead with this objective

**Comment by Sierracode** [comment]
This needs working it. I am to dumb to make it work by copying the debrain objective but I am sure grand master zaers can make it work.

**Comment by Sierracode** [comment]
Putting this on the back burner until I learn 2 code gud
