### ISSUE TITLE
fix it so that mediborgs can operate

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#108]
as it stands they can only apply drapes and that's it

**Comment by Zaers** [comment]
I couldn't reproduce it on my machine: 
![works on my machine](https://cloud.githubusercontent.com/assets/3045458/18892560/56ceccc0-84e0-11e6-9b4d-4793f4496f79.png)

**Comment by chaosyourgod** [comment]
I don't know what that guys problem was then
