### ISSUE TITLE
Toxins Test Range Wall no longer indestructable

### ISSUE THREAD

**Issue by Dagreenskin** [Sierracode/-tg-station#114]
I found this out when playing with toxins on a private server when my second bomb blew up solars becuase it sailed right past the toxins test site and back into the Z-level because the wall was gone after being blown up by the previous bomb. I was able to recreate this bug on the main server with an admin explosion.

**Comment by Zaers** [comment]
It's probably the backdrop wall being simulated instead of indestructible
