### ISSUE TITLE
[IDEA] Custom BPM For Instruments

### ISSUE THREAD

**Issue by HorridComedian** [Sierracode/-tg-station#115]
I want to play the music shit like this http://pastebin.com/bEkSAMcu and I cant because BPM has a limit or the BPM isnt the right number since it only has preset values. Allow for the user to input the number manually instead of preset values so we can have more music.

**Comment by Sierracode** [comment]
Tbh I might add this cause that music list is kinda large.

**Comment by HorridComedian** [comment]
I have a few others like 
http://www.ss13.eu/wiki/index.php/Songs 
http://ss13.moe/wiki/index.php/Piano
http://pastebin.com/KTk956UE
http://pastebin.com/HpP8YLAC

There is also a guide how to make music from many songs http://robustvinyl.com/ss13/wiki/index.php/Guide_to_Music

**Comment by Sierracode** [comment]
Will find a work around for this tonight

**Comment by Sierracode** [comment]
After speaking with zaers neither he nor I want to touch music code as it is autisticly bad. Sorry boyo <3
