### ISSUE TITLE
mushroommen

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#125]
red mushroom man 

[red mushroomman.zip](https://github.com/Sierracode/-tg-station/files/505533/red.mushroomman.zip)

**Comment by vultraz168** [comment]
What is this?

**Comment by chaosyourgod** [comment]
it's a man who's a mushroom and he has a red too and I was going to do more mushroom men for a stupid low pop game mode

**Comment by Sierracode** [comment]
*Hint to secret gamemode changes in the future but not mushroommen*
