### ISSUE TITLE
Setting someone's mental status to *INSANE* no longer makes beepsky arrest them

### ISSUE THREAD

**Issue by Dagreenskin** [Sierracode/-tg-station#128]
Is this a bug or was that removed?

**Comment by vultraz168** [comment]
I don't think this has ever been the case, from what I can tell by reading the code history.

**Comment by Dagreenskin** [comment]
![ss 2016-10-04 at 10 18 13](https://cloud.githubusercontent.com/assets/13697774/19101872/771e8150-8a80-11e6-97f7-d353f404f3a5.png)

It seems like it should be the case with how similar it looks to the security records

**Comment by Sierracode** [comment]
The wiki has always been outdates since is it pretty much just a slightly edited carbon copy of /tg/ wiki. Do not consider it gospel as to what can and cannot happen on the server. That is what the codebase is for.
