### ISSUE TITLE
nurf emag?

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#130]
I think that if emag wasn't the go to de facto syndicate item then other shit would be used and we'd see more interesting stuff happen

**Comment by Sierracode** [comment]
For someone who posts in deadchat and ooc about how robust you are you do seem to find a lot of "issues" like this one.

**Comment by chaosyourgod** [comment]
I never once said I was robust you twat, I call others unrobust, that does not mean that I'm saying that I am, get it fucking right you wretched cunt funnel
