### ISSUE TITLE
limit on mmomi spawning

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#133]
why not just have it so that the mmomi fab uses a certain amount of materials and that the only way to restock one is with a human doing it

**Comment by Sierracode** [comment]
Tbh I will probably just delete them on shifts whenever I am online just to save remapping and recompiling the server. When we move to the new map, I will be sure none are on the station but will give robo some extra posibrains to balance it out. Maybe 3 at shift start instead of the normal 2

**Comment by chaosyourgod** [comment]
that does not fix the issue on the whole, just reverts it back into the other issue and adding another posibrain does not fix this issue either 

/tg/ has adamantite golem on the lava planet to do whatever in which fixes this issue much better then how it's currently being handled so maybe we need something like that

I'm spriting some giant space wasps up as a means to replace xenomorphs but maybe it could fulfill this role much better
