### ISSUE TITLE
space wasp 

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#134]
[space wasp.zip](https://github.com/Sierracode/-tg-station/files/513948/space.wasp.zip)

space wasp

**Comment by Sierracode** [comment]
Closing to clean issues tab. Probably won't come back to this cause muh spacecarps

**Comment by chaosyourgod** [comment]
it;'s not to replace space carp but actually to either replace xenos or go along side it, I've been in talks with it on the thread and there's some neat ideas that came of it which I've saved
