### ISSUE TITLE
moving while doing shit 

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#136]
make it so that you can still do stuff which requires you to stand still be able to do while moving but take much longer depending on what it is you are doing and I don't mean just twice as long either, have it so that it's proportional to how fast you are going, so if you're just walking slowly it doesn't add much time but if you're high on hyperinze and transcending time and space then it'll take yonks

**Comment by Sierracode** [comment]
This is a pretty big change. It would mean changing a LOT of procs for interactions on a LOT of items. And for something that people might dislike or not even use. Unless someone does it voluntarily Its probably not going in.
