### ISSUE TITLE
Request: MoMMI Headgear slot improvement.

### ISSUE THREAD

**Issue by AssBlastProductions** [Sierracode/-tg-station#150]
While being an overall upgrade to drones in every other aspect there is one thing MoMMI's are a downgrade in. The headgear equipment slot.

Drones from what I remember could equip headwear, eyewear and masks onto their headgear equipment slot. Meaning a drone could equip a pair of shades or a gas mask or a hardhat while MoMMI's are limited to hats only. If possible I'd like the MoMMI headgear slot to be altered to allow them to equip all the things drones could equip onto their headgear slot.

If sprite locations are the issue maybe it could be limited to certain MoMMI exterior models or something.

**Comment by chaosyourgod** [comment]
I don't think there'd be an issue with the sprite locations but it is alot of work repositioning that shit just for this
