### ISSUE TITLE
MoMMIs (and possibly other cyborgs) not listed if destroyed before the round ends

### ISSUE THREAD

**Issue by DerFlammenwerfer** [Sierracode/-tg-station#153]
I'd like to suggest this be fixed if it is a bug, though I can understand this being intentional to avoid spam. This helps players write down the ckey of those breaking their laws so that they can be reported.

**Comment by Sierracode** [comment]
Maybe have it so it bundles "mommis" all with the same laws like

Players ckey1 ckey2 ckey3 ckey4 played as
mommi1 mommi1a mommi2 mommi3 mommi3a mommi4  All with the same laws so that We can distinguish who has been abusing mommi spawners to come back like 15 times in one shift.

**Comment by Sierracode** [comment]
Vultraz code fixes this issue
