### ISSUE TITLE
Remove the MoMMI fabricator from the main station

### ISSUE THREAD

**Issue by Dagreenskin** [Sierracode/-tg-station#159]
MoMMIs breaking laws and abusing the spawner is the exact reason why we only had them on the derelict and mining station

**Comment by AssBlastProductions** [comment]
Worst case scenario that's probably necessary considering not only the amount of shitters but the fact that they can respawn more than once.

If possible I'd prefer some kind of alternative to removing it from the station like a combination of some sort of cooldown timer on how often you can come back as a MoMMI like maybe once every 10 minutes or something plus some other failsafe like maybe spawner created MoMMI could always show up on the RD's cyborg console and blowing them not cause an actual explosion but just leave behind a pile of robot debris or something. Not sure if that's at all possible but I imagine it could potentially be linked to the killswitch thing in the code that prevents them from leaving the station which is absent on non spawner made MoMMI.

**Comment by Sierracode** [comment]
I will be purging these soon enough, probably tonight, the addition of the spawners has done nothing but add admin work. What I may do is have an unpowered one on the newmap in robotics. That way a robo/scientist can wrench it down or something to allow respawns. But Even that is a push.

**Comment by Sierracode** [comment]
Purged
