### ISSUE TITLE
[BUG] WT-550 Automatic Rifle missing sprite that shows it in your hands

### ISSUE THREAD

**Issue by HorridComedian** [Sierracode/-tg-station#160]
This means that the only way to find someone that has this weapon is if you shift-click them but by then you will be dead, there needs to be a physical sprite in the hand of the character or else its basically an invisible automatic rifle.

**Comment by Sierracode** [comment]
I have knew about this for a while. I am dumb and forgot to fix it will get this fixed tonight.
