### ISSUE TITLE
more low pop antags

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#42]
I'm tired of lings or traitors or ling/traitors 

we need more then just shit that murderbones always 

so I suggest space gnomes who get missions to steal peoples pants and/or painting the station pink

**Comment by Sierracode** [comment]
Maybe we could set it so that Assasinate Objectives require a certain ammount of people..that way atleast limiting "valid" muderbones.

**Comment by chaosyourgod** [comment]
the people who want to murder bone will still murder bone regardless of that, which is what is happening round after round when there's people on without an admin

**Comment by chaosyourgod** [comment]
also someone suggested that when we do get higher numbers for different game modes that trat and ling get removed off of the circle
