### ISSUE TITLE
something for when people want to afk but still be on the server

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#45]
I've suggested about a cinema that plays youtube videos or something so that people could just idle in and watch whatever is playing while also uploading stuff to watch 

also having a radio shack which plays songs through the speakers would really help when things are slow

**Comment by Sierracode** [comment]
>complains about adminmidis downloading to everyone
>Hey guys lets upload VIDEOS
:^)

**Comment by chaosyourgod** [comment]
point out where I was complaining about adminmidis you fag
