### ISSUE TITLE
Only download Adminmusic if you have the preference enabled

### ISSUE THREAD

**Issue by Sierracode** [Sierracode/-tg-station#48]
People on the thread and ingame have been bitching about mine and the midimins shiteir music interest eating into their 500mb per month 40kb/s Colombian Bamboo internet. 

PlS fIx ZaErS

**Comment by Zaers** [comment]
This either should already happen according to https://github.com/Sierracode/-tg-station/blob/master/code/modules/admin/verbs/playsound.dm#L20 or there's nothing I can do about it because it uses a byond inbuilt proc to make the sound

**Comment by Sierracode** [comment]
REEEEEEE

**Comment by Sierracode** [comment]
This is being closed as Synchtube has replaced adminmusic. Update is now active.
