### ISSUE TITLE
FIX LAG PLS

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#50]
TY

**Comment by Sierracode** [comment]
GET BETTER INTERNET PLS. THE SERVER RUNS FROM TWO  10GB/S NOW ONE IS DEDICATED TO FUCKING BYOND AND NOTHING ELSE GOES THROUGH IT. MAYBE PLEDGE $5 A MONTH TO GET DECENT INTERNET

**Comment by chaosyourgod** [comment]
>get better internet
>server lags when there's any kinda bomb and lags to hell when cult summons nar-san

o.k

**Comment by Sierracode** [comment]
Bombs and Nar-san are more CPU problems on the server itself. A LOT of stuff happens. With bombs Reactive explosions affect the movement of items and calculates how each tile is affected depanding on what is on it. With narsie it changed items by deleting them and setting them to hit own tiles. These are naturally intensive. I am sure a work around could be made but it isn't easy nor a priority it seems.
