### ISSUE TITLE
[IDEA] Buff Mushroom Hallucinogenic 

### ISSUE THREAD

**Issue by Dagreenskin** [Sierracode/-tg-station#51]
Mushroom hallucinogenic should be between space drugs and mindbreaker is basic potency and effectiveness.  I suggest adding confusion and small levels of hallucinations, as well as making it have a chance to play http://puu.sh/r3jk3/43b05db6b5.ogg which was gonna be added but then Hatestation died.

**Comment by chaosyourgod** [comment]
oh I remember that .ogg

**Comment by Sierracode** [comment]
Closing but might request this to get worked on in the future.
