### ISSUE TITLE
mercenaries, why isn't there any?

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#54]
how they could work is that you get enough space cash together and craft it into a contract using a bounty board placed in the vacant pawn shop, that the player has to write up objectives for which then either summons or can be given to mercenaries who then can either accept it or not but if they accept it and achieve what it states they gain merc points which allow them better gear and neat toys 

but here's what I think, there should be different tiers of contracts that allow for more objectives and the higher the tier the higher it's bidding cost is, so say you have the lowest level of contract that has the objective "kill X", "X" could go see what the active contracts are on the bounty board and then just pay the bid and then out bid the current holder and change the contract to "steal x" 

when a contract is complete and the merc is after his due they have to dna sign a completion signature on the contract

**Comment by chaosyourgod** [comment]
also to become a merc it could just be a simple matter of signing up on the bounty board

**Comment by Sierracode** [comment]
A corperation such as nanotransen has a policy against its own crew acting as vigilantes. And have their own private security. Mercs are rarely seen inspace anways :^)

**Comment by chaosyourgod** [comment]
you'd like it more if I did some sprites you sprite slut
