### ISSUE TITLE
[IDEA] Taser Rework 

### ISSUE THREAD

**Issue by Dagreenskin** [Sierracode/-tg-station#55]
Rather than making you instantly fall over and drop your items, I propose that tasers should instead hold you in place, and if you are holding a gun in your active hand, make you uncontrollably fire in the direction you are facing, otherwise it will make you activate your held item (Which may lead to some hilarious situations in which sec tazes someone holding a grenade only for everyone to get a healthy dose of mindbreaker smoke) . This will not only alleviate the feeling of tasers being the end all combat weapon, but give Disablers a bit more utility as it a slower stun  can still disarm and knock out someone without worry of being shot by stray gunfire, as well as giving going full lethal instead of "Stun then lethal" more of an effect as well.

**Comment by chaosyourgod** [comment]
I agree with 

and if you are holding a gun in your active hand, make you uncontrollably fire in the direction you are facing, otherwise it will make you activate your held item

however it should make them fire in random directions but you should still drop to the ground

**Comment by Sierracode** [comment]
See Hard suit tazer reworks
