### ISSUE TITLE
idea for triat and lings

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#57]
how about having it so that if they complete their objectives in certain ways they get different badges/title like in mgs3/4/5/pw? 

like if they don't kill anyone outside of their objectives they get a lan badge with the title cori ops or something along those lines

**Comment by Dagreenskin** [comment]
SS13 doesn't actually track who killed who, just who is dead and who is not.

**Comment by chaosyourgod** [comment]
does it track how who died?

**Comment by Sierracode** [comment]
There is no long term shift after shift tracking other than server end logs. In a shift fingerprints and attack logs show who attacked and killed you. It is certainly possible but seems unnessasary at best. Closing to tidy Issue panel.
