### ISSUE TITLE
MoMMIs+Safes

### ISSUE THREAD

**Issue by T-Wiz** [Sierracode/-tg-station#59]
MoMMI's cannot operate safes, such as the one in the vault or floor safes. The UI for the safe opens, but nothing happens when the + or - symbols are clicked.

**Comment by vultraz168** [comment]
This appears to be intended.
`/obj/structure/safe/Topic(href, href_list)
		if(!ishuman(usr))
				return`

**Comment by T-Wiz** [comment]
Would be nice if it included a comment, such as 'You don't have the dexterity for this!'
