### ISSUE TITLE
Posting a rar of a bunch of sprites I made but were never actually added

### ISSUE THREAD

**Issue by Dagreenskin** [Sierracode/-tg-station#60]
I put all the sprites I made (Excluding Dragon dildos) into a rar for any coders who want to implement them

Including: 
Atmosborg
Baseballbat
T8R baton and Stormtrooper armor to go with it
2 new AI Core displays (Icarus and Flowey) and three new status displays (Stop, Comfy and Flowey)

http://puu.sh/r80Rv/5477f34983.rar

**Comment by Sierracode** [comment]
Do you still have an idea as to what you want the atmos borg to do.  I am thinking he can use the Canisters for both jetpacks but can also open them in a room, allowing a emagged one to maybe switch its o2 canisters for plasma/sleepmix for super cool murder tactics.

**Comment by Dagreenskin** [comment]
Thats what I was thinking, Normally it should be able to generate custom mixes of "safe" gasses as well as being able to scrub the air of contaminants,  and when it gets emagged, it unlocks being able to use CO2, NO2 and Plasma and gives it a zippo lighter (In addition to the welder it already has)

**Comment by Sierracode** [comment]
Atmosborg added. Will come back to the rar should I lack an cool ideas. Many thanks.
