### ISSUE TITLE
MoMMi+Crematorium; Could be abused?

### ISSUE THREAD

**Issue by T-Wiz** [Sierracode/-tg-station#66]
Mommis can climb into the Crematorium and activate it, destroying their body and forcing them into a regular ghost/observer form. The death also spawns a LIVING MMI that the player can then re-enter and speak through.

**Comment by vultraz168** [comment]
Wouldn't this technically be a violation of KEEPER law II?

**Comment by Sierracode** [comment]
As Vultraz states this would break their laws. More than likely to be handled through ahelps. should people abuse this We will probably stop it happening. Until then. nochange chall occcur.
