### ISSUE TITLE
Request: Ventcrawling update.

### ISSUE THREAD

**Issue by AssBlastProductions** [Sierracode/-tg-station#76]
A while ago (mid 2015?) /tg/ updated ventcrawling so that instead of alt+clicking on a vent and getting a list of other vents to click on and then appearing at the vent you select you would alt+click on a vent or scrubber and then begin to squeeze into the vent or scrubber. Squeezing into a vent or scrubber if I remember right took about 1.5-2 seconds to do, I would guess to make escape slightly less easy since with the previous system it would take about that long to press a button on your keyboard and select your desired vent and click it.

Once inside the vent or scrubber you would then move around the actual pipes in real time adding a whole new layer of depth to ventcrawling whereas previously it was more of a simple teleport. I think certain mobs such as monkeys were even affected by pressure and contents of pipes and would die if entering scrubbers instead of vents and so on.

Anyway I personally think this is a huge improvement on the current ventcrawling system and would like to request that porting it would be considered or looked into and I think most people would prefer this new system over the current simple list and instant appearing we have now.

One thing that should be noted is that last I checked xeno larvae could grow inside pipes which might need to be disabled as it might make it incredibly easy to hide as a larva, or it could be kept if people feel that early xeno stages are too difficult as they are now.

**Comment by Sierracode** [comment]
Closing to clean up issue tab
