### ISSUE TITLE
Gang dominator can't ever be ordered

### ISSUE THREAD

**Issue by Richard333** [Sierracode/-tg-station#80]
The gang dominator can never be ordered when it should be able to be ordered whenever.

**Comment by Sierracode** [comment]
After speaking with zaers. There is a contingency for it being spawned which is that the gang has to be legit round type not spawned in as that round was. 
ITS A FEATURE.

**Comment by Zaers** [comment]
the line that specifically governs that is https://github.com/Sierracode/-tg-station/blob/master/code/game/gamemodes/gang/recaller.dm#L154
