### ISSUE TITLE
[IDEA] Emagged Borg Reworks

### ISSUE THREAD

**Issue by Dagreenskin** [Sierracode/-tg-station#82]
Just tossing a few ideas I had to change up the Securiborg+Maybe a default borg meta for emagging borgs and update them around the nerfs and such the server has gotten, as well as making it a bit riskier to do so, but giving better rewards for doing so. If its not obvious I hate the stunarm becuase its a lazy addition and Secborg already has the baton for stuns.

1. Emagging a borg with a closed cover should not only unlock the cover, but lock down the borg and disable its radio for 5 seconds
2. Emagging a borg has a chance of triggering Nanotrasen Anti-Tamper and cause the borg to explode with the force of an emagged borg (35% chance with the cover closed, 25% with it open, 0% if the emagger is a cyborg 100% if the emagger is a clown with the clumsiness gene)
3. Borg reworks:

A. Janitor Borgs: Space Lube is replaced with an dock that can hold and generate Beartraps (Generating instead of simply picking them up has a high energy cost)
B. Mediborgs: Polyacid spray is replaced with the hypospray able to generate and inject sleep toxin
C. Service Borgs have their chloral hydrate beer replaced with an multiple-use bottle that can be smashed over people's heads and dousing them in alcohol, which they can then follow up with their Zippo lighter
D. Mining borgs have their stunarm replaced with a dock that can hold and generate small emagged mining charges
E.  Engineer borgs have their stunarm replaced with an emag.
F. MoMMI's get their stunarm removed. Just being able to be a quick ventcrawling little shit with a bunch of items and a hand slot, that isnt bound by any laws is already enough, but have the restriction for not being able to create more MoMMIs removed.
G. All emagged borgs can now detonate themselves as a last resort.

**Comment by Sierracode** [comment]
Closing to clean up issue tab
