### ISSUE TITLE
fix abductors 

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#88]
right now it's so fucking awkward and buggy since sometimes when you teleport a abducter in you'll get kicked off the console and have to teleport him back inorder to be able to use it properly again

**Comment by Zaers** [comment]
Does it tell you any message when kicking you from the console?

**Comment by chaosyourgod** [comment]
nothing, just kept on doing it at weird points

**Comment by chaosyourgod** [comment]
it seems like it didn't fix it

**Comment by Zaers** [comment]
Noted, I'm watching the console to see what happens when it breaks
