### ISSUE TITLE
replacing the astroid mining with something that actually effects more of the station

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#92]
what if we replace the asteroid mining shit with tiberium harvesting on a alien tib invested planet teeming with mutated alien wild life and plant life, which can be dissected for weird organs which does stuff that I haven't quite decided yet but the tib is collected via harvesters and transported to engineering for processing which needs upgrading from science to be able to produce more minerals but it works like this

>raw tiberium shards fed into a tib crusher that turns it into tib powder which is then moved into a silo for safe storage
>the tib powder can then be scent to science to be analyzed in a tib analyzer, which is like the EXPERIMENT device only actually used regularly, once the right combinations are done with the correct research levels, science can then print boards out which are used to make the machines that turn the tib powder into any material
> these machines are and what they do
 tib liquidator, tiberium into a liquid
tib condenser, tiberium into big chunks
tib freeze heater, heats or cools all tiberium 
tib vaporizer, tiberium into a gas
tib energizer, zaps tiberium with power 
tib seperator, tiberium into raw minerals  

so inorder to make diamonds from tib, you have to take the tib powder then condense it into tib chunks which then need heating then condensed again into diamond tiberium crystals clusters and finally put into the tib separator which filters out the tiberium and putting out the raw diamonds

**Comment by Sierracode** [comment]
Until sheylos pushes muh super station map. Mapping issues are sidelined,
